<?php

/**
 * Implements hook_menu().
 */

function biblioteca_menu() {
    $items = array();
    
    //page for displaying biblioteca database table content.
    $items['biblioteca'] = array( 
        'title' => 'Biblioteca',
        'page callback' => 'mytable_display', 
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    //page with form for adding books.
    $items['biblioteca/add'] = array(
        'title' => t('Add Book'),
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('biblioteca_add_form'),
        'access arguments' => array('administer biblioteca module'), //function for permissions.
        'type' => MENU_NORMAL_ITEM,
    );
    //page withform for editing book status.
    $items['biblioteca/edit/%'] = array(
        'title' => t('Edit Book'),
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('biblioteca_edit_form', 2),
        'access callback' => 'user_is_logged_in',
    );

    $items['biblioteca/mail/%'] = array(
        'title' => t('Send notification page'),
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('biblioteca_mail_form',2),
        'access arguments' => array('administer biblioteca module'), //function for permissions.
    );

    $items['biblioteca/qr/%'] = array(
        'title' => t('Send notification page'), 
        'page callback' => 'qr_code_preprocess',
        'page arguments' => array('qr_code_preprocess', 2),
        'access arguments' => array('administer biblioteca module'), //function for permissions.
    );

  /*  $items['qr'] = array( 
        'title' => 'QR Code',
        'page callback' => 'qr_code_preprocess', 
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

  */


    return $items;
}


/**
 * Implements hook_form().
 */

function biblioteca_add_form($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Book Title'),
    '#required' => TRUE, 
  );
  $form['author'] = array(
    '#type' => 'textfield',
    '#title' => t('Author'),
    '#required' => TRUE,
  );
  $form['isbn'] = array(
    '#type' => 'textfield',
    '#title' => t('ISBN number'),
    '#description' => 'ISBN should be a 10 or 13 digit number. Please do not enter non-digit characters.',
    '#required' => TRUE, 
  );
  $form['status'] = array(
    '#type' => 'select',
    '#title' => t('Book Status'),
    '#required' => TRUE, 
    "#default_value" => "plugin1",
    "#options" => array(
        "Available" => t("Available"),
        "Request" => t("Request"),
        "Reserved" => t("Reserved"),
        "Unavailable" => t("Unavailable"),   
        ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#validate' =>  array('biblioteca_form_validate'),
    '#submit' =>  array('biblioteca_form_submit'),
  );
  return $form;
}

/**
 * Implements biblioteca_form_validate().
 * Checks if ISBN number contains 10 or 13 only digit characters.
 */
function biblioteca_form_validate($form, $form_state) { 
    if ((strlen($form_state['values']['isbn']) != 10) 
            && (strlen($form_state['values']['isbn']) != 13)
            || (!ctype_digit($form_state['values']['isbn']))){
                form_set_error('isbn', 'Please enter valid ISBN-10 or ISBN-13 number.');
    } 


}

/**
 * Implements biblioteca_form_submit().
 */

function biblioteca_form_submit($form, $form_state) {

  db_insert('biblioteca')
    ->fields(array(
      'title' => $form_state['values']['title'], 
      'author' => $form_state['values']['author'],  
      'isbn' => $form_state['values']['isbn'],  
      'status' => $form_state['values']['status'],      
    ))
    ->execute();
    drupal_set_message("Book added successfully to database! yuhuuuu!");
}


/**
 * Implements hook_form().
 */

function biblioteca_edit_form($form, &$form_state, $variable) {

  global $user;


    if (in_array('Bibliotecar', $user->roles) || in_array('administrator', $user->roles)) {

      $form['id'] = array(
        '#type' => 'hidden',
        '#title' => t('ID'),
        '#default_value' => $variable,
        '#description' => 'Enter ID of the book you want to edit. ID can be seen on My Books Table page',
        '#required' => TRUE, 
        );

      //getting the current status of the book
      $result = db_select('biblioteca','s')
        ->condition('id', $variable, '=')
        ->fields('s', array('status'))
        ->execute();

        foreach($result as $item) {
          $current_status = $item->status;
        }


      $form['status'] = array(
        '#type' => 'select',
        '#title' => t('Book Status'),
        '#required' => TRUE, 
        "#default_value" => $current_status,
        "#options" => array(
            "Available" => t("Available"),
            "Request" => t("Request"),
            "Reserved" => t("Reserved"),
            "Unavailable" => t("Unavailable"),   
            ),
      );

      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
        '#submit' =>  array('biblioteca_edit_form_submit'),
      );

      return $form;

  }
  else{

      $form['id'] = array(
      '#type' => 'hidden',
      '#title' => t('ID'),
      '#default_value' => $variable,
      '#description' => 'Enter ID of the book you want to edit. ID can be seen on My Books Table page',
      '#required' => TRUE, 
      );

      //getting the current status,title and author of the book
      $result = db_select('biblioteca','s')
        ->condition('id', $variable, '=')
        ->fields('s', array('title','author','status'))
        ->execute();

        foreach($result as $item) {
          $current_status = $item->status;
          $current_title = $item->title;
          $current_author = $item->author;
        }


        if ($current_status != "Available"){ 
            drupal_set_message("This book is currently unavailible for request!", $type = "error");

        }else{

            $form['status'] = array(
              '#type' => 'hidden',
              '#title' => t('Book Status'),
              '#required' => TRUE, 
              "#default_value" => "Request",
              "#options" => array(
                  "Request" => t("Request"),  
                  ),
                );
        
            drupal_set_message("Dou you want to request ".$current_title." from ". $current_author."?", $type = "warning");

            $form['submit'] = array(
              '#type' => 'submit',
              '#value' => 'Request Book',
              '#submit' =>  array('biblioteca_edit_form_submit'),
            );

            return $form;
        };
      
  };
  
}

/**
 * Implements biblioteca_edit_form_submit().
 */

function biblioteca_edit_form_submit($form, $form_state) {

  global $user;

  if (in_array('Bibliotecar', $user->roles) || in_array('administrator', $user->roles)) {
      //if current user is admin or bibliotecar
      if ($form_state['values']['status'] == "Reserved"){
          //if status changes into Reserved the current date is inserted
          db_update('biblioteca')
          ->fields(array(
            'status' => $form_state['values']['status'],
            'date' => date('Y-m-d'),
              )
          )
          ->condition('id', $form_state['values']['id'])
          ->execute();
          drupal_set_message("Book status was updated successfully! yuhuuuu!");

      }else{
          //if status is changed into != Reserved delete date and userid field from database
          db_update('biblioteca')
          ->fields(array(
            'status' => $form_state['values']['status'],
            'date' => NULL,
            'userID' => NULL,
              )
          )
          ->condition('id', $form_state['values']['id'])
          ->execute();
          drupal_set_message("Book status was updated successfully! yuhuuuu!");
      };
      

  }else{
      //if current user is not bibliotecar or admin
      //and changes status into Request the user id is saved in the database
      db_update('biblioteca')
      ->fields(array(
        'status' => $form_state['values']['status'],
        'userID' => $user->uid, 
          )
      )
      ->condition('id', $form_state['values']['id'])
      ->execute();
      drupal_set_message("Book status was updated successfully! yuhuuuu!");
  };

}


/**
 * Implements hook_permission().
 */

function biblioteca_permission() {
  return array(
    'administer biblioteca module' => array(
      'title' => t('Administer biblioteca module'),
      'description' => t('Perform administration tasks for biblioteca module.'),
    ),
  );
}


/**
 * Function to display biblioteca database table in table format with pager.
 */

function mytable_display() {

  $header = array(
                array(
                    'data' => t('ID'),
                    'field' => 't.id',
                ),
                array(
                    'data' => t('Title'),
                    'field' => 't.title',
                ),
                array(
                    'data' => t('Author'),
                    'field' => 't.author',
                ),
                array(
                    'data' => t('ISBN number'),
                    'field' => 't.isbn',
                ),
                array(
                    'data' => t('Status'),
                    'field' => 't.status',
                ),
                array(
                    'data' => t('Edit'),

                ),
            );


  global $user;
   if (in_array('Bibliotecar', $user->roles) || in_array('administrator', $user->roles)) {
      
       $header2 = array(
                array(
                    'data' => t('Date'),
                    'field' => 't.date',
                ),
                array(
                    'data' => t('UserID'),
                    'field' => 't.userID',
                ),
                array(
                    'data' => t('Mail'),
                ),
                array(
                    'data' => t('QR Code'),
                ),
            );
      //mearging the headers to get the extended table for bibliotecar.
      $header = array_merge($header, $header2);

      $query = db_select('biblioteca', 't');

      $query->fields('t', array('id','title','author','isbn','status','date','userID'));  // select your required fields here.

      $table_sort = $query->extend('TableSort') // Add table sort extender.
                          ->orderByHeader($header); // Add order by headers.

      $pager = $table_sort->extend('PagerDefault')
                          ->limit(20);  // here you can limit the number of data per page.

      $result = $pager->execute();

      $rows = array();
            foreach ($result as $row) {

                $editlink = "<a href='".drupal_get_path_alias(current_path()) . '/edit/'. $row->id."'>Edit</a>";
               
                //check if book is reserved and only then show mail and qr code link
                if($row->date){
                    $maillink = "<a href='".drupal_get_path_alias(current_path()) . '/mail/'. $row->id."'>Mail</a>";
                    $qrlink = "<a href='".drupal_get_path_alias(current_path()) . '/qr/'. $row->id."'>Generate</a>";
                }else{
                    $maillink = "";
                    $qrlink = "";
                };

                
                
                $rows[] = array('data' => array($row->id, $row->title, $row->author, $row->isbn, $row->status, $editlink, $row->date, $row->userID, $maillink, $qrlink));

            }
      // If rows are not empty theme and display the rows.

       $output = theme('pager');
            $output .= theme('table', array('header' => $header, 'rows' => $rows, "empty" => t("No Records Found"), 'attributes' => array('id' => 'sort-table', 'class' => array('tbl-data'))));
            $output .= theme('pager');

        return $output;
  


  }else{

      $query = db_select('biblioteca', 't');

      $query->fields('t', array('id','title','author','isbn','status'));  // select your required fields here.

      $table_sort = $query->extend('TableSort') // Add table sort extender.
                          ->orderByHeader($header); // Add order by headers.

      $pager = $table_sort->extend('PagerDefault')
                          ->limit(20);  // here you can limit the number of data per page.

      $result = $pager->execute();

      $rows = array();
            foreach ($result as $row) {
                $editlink = "<a href='".drupal_get_path_alias(current_path()) . '/edit/'. $row->id."'>Edit</a>";
                
                $rows[] = array('data' => array($row->id, $row->title, $row->author, $row->isbn, $row->status, $editlink));

            }
      // If rows are not empty theme and display the rows.

       $output = theme('pager');
            $output .= theme('table', array('header' => $header, 'rows' => $rows, "empty" => t("No Records Found"), 'attributes' => array('id' => 'sort-table', 'class' => array('tbl-data'))));
            $output .= theme('pager');

        return $output;
    }
}

/**
 * Implements hook_form().
 * Form for sending mail.
 */

function biblioteca_mail_form($form, &$form_state, $variable) {

  $form['id'] = array(
    '#type' => 'hidden',
    '#title' => t('ID'),
    '#default_value' => $variable,
    '#required' => TRUE, 
  );

  //getting the current status of the book
  $result = db_select('biblioteca','s')
    ->condition('id', $variable, '=')
    ->fields('s', array('title','author', 'date','userID'))
    ->execute();

    foreach($result as $item) {
      $current_title = $item->title;
      $current_author = $item->author;
      $current_date = (string)$item->date;
      $current_uid = $item->userID;    
    }
    
    $usr = user_load($current_uid);

  $form['mailto'] = array(
    '#type' => 'textfield',
    '#title' => t('Mail to'),
    '#default_value' => $usr->mail,
    '#required' => TRUE, 
  );

  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#default_value' => 'Reminder to return book!',
    '#required' => TRUE, 
  );

  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Body'),
    '#default_value' => 'This is a reminder to return the following book: '.$current_title.' from '.$current_author.' reserved on '.$current_date,
    '#required' => TRUE, 
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Send',
    '#submit' =>  array('biblioteca_mail_form_submit'),
  );
  return $form;
}

/**
 * Implements biblioteca_mail_form_submit().
 */

function biblioteca_mail_form_submit($form, $form_state) {

  $mailto = $form_state['values']['mailto'];
  $subject = $form_state['values']['subject'];
  $body = $form_state['values']['body'];
  $body = wordwrap($body,70);
 
  if(mail($mailto, $subject, $body)){
    drupal_set_message('Email sent to '.$mailto);
  }else{
    drupal_set_message('Error in sending email', $type = 'error');
  };

  //mail($mailto, $subject, $body);
}


/**
 * Implements qr_code_preprocess() function.
 */


global $base_url;

function qr_code_preprocess(){

  //getting the id from url with arg() function for the query by id.
  $var = arg(2);  
  //getting the current book data
  $result = db_select('biblioteca','s')
    ->condition('id', $var, '=')
    ->fields('s', array('title','author', 'date', 'userID'))
    ->execute();

    foreach($result as $item) {
      $current_title = $item->title;
      $current_author = $item->author;
      $current_date = (string)$item->date;
      $current_uid = $item->userID;

    }
    
    //loading the user by id to get the username.
    $usr = user_load($current_uid);

  $text = $current_title.' from '.$current_author.' was reserved by '.$usr->name.' on  '.$current_date;

  //calling the qr code generate function.
  qr_code_generate($text);

}



function qr_code_generate($text){

  include("sites/all/libraries/phpqrcode/qrlib.php");
    
    // outputs image directly into browser, as PNG stream
    QRcode::png($text);
}